TempleApp/src/main/java/example/TempleApp/Activities/DeleteData.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadSingleData.java, TempleApp/src/main/java/example/TempleApp/Activities/UpdateData.java, TempleApp/src/main/res/layout/delete_data.xml, TempleApp/src/main/res/layout/insert_data.xml, TempleApp/src/main/res/layout/read_all.xml, TempleApp/src/main/res/layout/read_data.xml, TempleApp/src/main/res/layout/update_data.xml
Fixed #10 
Fixed typos in some of the layouts.Also deleted "int x " and "int jindex" in some of java files which are unused and causes typos like:
Screenshots of the change:
=> Fixes issue #10

README.md
=> Inserted Screenshots into README.md file

TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java
=> Revert "fixes #12: It will be better to restrict user to add either "user ID" or "name", without leaving both details empty"

README.md
Added Gitter Channel for Communication with Contributors
=> feat: Added Gitter Channel

TempleApp/src/main/java/example/TempleApp/Activities/DeleteData.java, TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java, TempleApp/src/main/java/example/TempleApp/Activities/MainActivity.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadSingleData.java, TempleApp/src/main/java/example/TempleApp/Activities/UpdateData.java, TempleApp/src/main/res/layout/activity_main.xml, TempleApp/src/main/res/layout/delete_data.xml, TempleApp/src/main/res/layout/insert_data.xml, TempleApp/src/main/res/layout/read_all.xml, TempleApp/src/main/res/layout/read_data.xml, TempleApp/src/main/res/layout/update_data.xml, TempleApp/src/main/res/values/strings.xml
Fixed #22
Changes: Removed hardcoded strings
=> Hardcoded string fix

TempleApp/src/main/java/example/TempleApp/Activities/DeleteData.java, TempleApp/src/main/java/example/TempleApp/Activities/MainActivity.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadSingleData.java, TempleApp/src/main/java/example/TempleApp/Activities/UpdateData.java, TempleApp/src/main/java/example/TempleApp/Adapter/MyArrayAdapter.java, TempleApp/src/main/java/example/TempleApp/Adapter/MyDataModel.java, TempleApp/src/main/java/example/TempleApp/JSON_API/Controller.java, TempleApp/src/main/java/example/TempleApp/JSON_API/InternetConnection.java
=> Fixed comments with proper annotations

TempleApp/src/main/java/example/TempleApp/Activities/DeleteData.java, TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java, TempleApp/src/main/java/example/TempleApp/Activities/MainActivity.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/Activities/ReadSingleData.java, TempleApp/src/main/java/example/TempleApp/Activities/UpdateData.java, TempleApp/src/main/java/example/TempleApp/Adapter/MyArrayAdapter.java, TempleApp/src/main/java/example/TempleApp/Adapter/MyDataModel.java, TempleApp/src/main/java/example/TempleApp/JSON_API/Controller.java, TempleApp/src/main/java/example/TempleApp/JSON_API/InternetConnection.java, TempleApp/src/main/res/layout/activity_main.xml, TempleApp/src/main/res/layout/delete_data.xml, TempleApp/src/main/res/layout/insert_data.xml, TempleApp/src/main/res/layout/layout_row_view.xml, TempleApp/src/main/res/layout/read_all.xml, TempleApp/src/main/res/layout/read_data.xml, TempleApp/src/main/res/layout/update_data.xml
=> remove branding

TempleApp/build.gradle, TempleApp/src/main/java/example/TempleApp/JSON_API/Api.java, TempleApp/src/main/java/example/TempleApp/classes/Result.java, TempleApp/src/main/java/example/TempleApp/classes/assets/AllAssetsResult.java, TempleApp/src/main/java/example/TempleApp/classes/assets/Asset.java, TempleApp/src/main/java/example/TempleApp/classes/assets/AssetsResult.java, TempleApp/src/main/java/example/TempleApp/classes/dmy/AllDMYResult.java, TempleApp/src/main/java/example/TempleApp/classes/dmy/DMYPooja.java, TempleApp/src/main/java/example/TempleApp/classes/dmy/DMYResult.java, TempleApp/src/main/java/example/TempleApp/classes/donation/AllDonationResult.java, TempleApp/src/main/java/example/TempleApp/classes/donation/Donation.java, TempleApp/src/main/java/example/TempleApp/classes/donation/DonationResult.java, TempleApp/src/main/java/example/TempleApp/classes/fd/AllFDResult.java, TempleApp/src/main/java/example/TempleApp/classes/fd/FD.java, TempleApp/src/main/java/example/TempleApp/classes/fd/FDResult.java, TempleApp/src/main/java/example/TempleApp/classes/ie/AllIEResult.java, TempleApp/src/main/java/example/TempleApp/classes/ie/IE.java, TempleApp/src/main/java/example/TempleApp/classes/ie/IEResult.java, TempleApp/src/main/java/example/TempleApp/classes/mwb/AllMWBResult.java, TempleApp/src/main/java/example/TempleApp/classes/mwb/MWB.java, TempleApp/src/main/java/example/TempleApp/classes/mwb/MWBResult.java, TempleApp/src/main/java/example/TempleApp/classes/pooja/AllPoojaResult.java, TempleApp/src/main/java/example/TempleApp/classes/pooja/Pooja.java, TempleApp/src/main/java/example/TempleApp/classes/pooja/PoojaResult.java
Fixes #13 
Changes: 
Added an API interface in the package JSON_API
Added java classes for the json objects to be returned
The API interface can now be used to call the api which uses retrofit
This file has all the methods(in the changed backend) which can be used
=> Added files for using retrofit

TempleApp/src/main/java/example/TempleApp/JSON_API/Api.java
in the API interface get annotations are added
=> added get in API interface

TempleApp/src/main/java/example/TempleApp/activities/DeleteData.java, TempleApp/src/main/java/example/TempleApp/activities/InsertData.java, TempleApp/src/main/java/example/TempleApp/activities/MainActivity.java, TempleApp/src/main/java/example/TempleApp/activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/activities/ReadSingleData.java, TempleApp/src/main/java/example/TempleApp/activities/UpdateData.java, TempleApp/src/main/java/example/TempleApp/adapter/MyArrayAdapter.java, TempleApp/src/main/java/example/TempleApp/adapter/MyDataModel.java, TempleApp/src/main/java/example/TempleApp/json_api/Api.java, TempleApp/src/main/java/example/TempleApp/json_api/Controller.java, TempleApp/src/main/java/example/TempleApp/json_api/InternetConnection.java
Fixed #30 
Directories names are now starting with small letters that were earlier caps.
=> Directory names changed to start with small letters 

TempleApp/src/main/AndroidManifest.xml
=> Renames the directory names

TempleApp/src/main/res/layout/delete_data.xml, TempleApp/src/main/res/layout/read_data.xml
Fixed #16 
Added scroll bars in "delete" and "read" layouts allowing the user to scroll when the user changes the orientation.
=> Added scrolling functionality for landscape mode

TempleApp/src/main/res/layout/read_all.xml
Fixed #46 
The scroll function is added to the layout allowing the user to view the "ReadAll" button in the read_all layout.
=> Scroll added to the read_all layout

TempleApp/build.gradle, TempleApp/src/main/java/example/TempleApp/activities/ReadAllData.java, TempleApp/src/main/java/example/TempleApp/adapter/MyArrayAdapter.java, TempleApp/src/main/res/anim/listview_animator.xml, TempleApp/src/main/res/drawable/button_animated.xml, TempleApp/src/main/res/drawable/ic_circle.xml, TempleApp/src/main/res/layout/activity_main.xml, TempleApp/src/main/res/layout/delete_data.xml, TempleApp/src/main/res/layout/insert_data.xml, TempleApp/src/main/res/layout/layout_row_view.xml, TempleApp/src/main/res/layout/read_all.xml, TempleApp/src/main/res/layout/read_data.xml, TempleApp/src/main/res/layout/update_data.xml, TempleApp/src/main/res/values/colors.xml, TempleApp/src/main/res/values/styles.xml
Added Animations and improved UI
I changed gradle files because animations did not support if min sdk is lesser than 21
=> Add Animations and improved UI

.travis.yml, app/build.gradle, build.gradle
=> add spotless and update gradle

.github/release-drafter.yml
=> chore: Create release-drafter.yml

app/src/main/res/drawable/ic_circle.xml, app/src/main/res/layout/layout_row_view.xml, app/src/main/res/values/dimens.xml
Fixed #76 
Changes: gave suitable dimensions so it will apply in all devices in ReadAll Activity
=> fix: Fixes UI issue in ReadAll Activity

app/src/main/res/layout/activity_main.xml
Fixed #77 
On switching to landscape mode, the scrolling works for the home screen.
=> fix: Scroll functionality enabled

app/src/main/java/org/amfoss/templeapp/json_api/Controller.java
Fixed #95 
Changes: 
Updated the URL of the backend so, it will work perfectly from now
Note: work is done on backend and deployed
=> fix: updated URL of backend

app/src/main/res/layout/delete_data.xml, app/src/main/res/layout/insert_data.xml, app/src/main/res/layout/read_data.xml, app/src/main/res/layout/update_data.xml, app/src/main/res/values/strings.xml
Fixed #93 
Changes: Replaced the user Id keyword with the Employee Id
=> fix: Replaced User ID with the Employee ID

app/src/main/res/values/strings.xml
Fixed #94 
The alert messages made relevant.
=> fix: Changed Alert dialogue messages

app/build.gradle
=> chore: Spotless

app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java, app/src/main/res/values/strings.xml
Fixed #90 
Edited the toast messages in the search section
=> fix: Edited the toast messages in the search section
